HomeTask5
pakondratyuk/scala-school pull request #5
Opened 2017-03-31 08:30 UTC by pakondratyuk

2017-03-31 09:28 UTC, sergeypopov83 commented on src/main/scala/lectures/oop/BST.scala
> +    require(nodesCount > 0)
выражение require надо заменить  на обычный IF
из  сигнатуры метода не видно что он должен бросать IllegalArgumentException
Ты можешь заменить  возвращаемый тип на Option[Bst]

2017-03-31 09:47 UTC, sergeypopov83 commented on src/main/scala/lectures/oop/BST.scala
> +  def randomVal = (Math.random()*1000) toInt
генератор надо сделать не от тысячи а, от maxValue

2017-03-31 09:47 UTC, sergeypopov83 commented on src/test/scala/lectures/matching/SortingStuffGeneratorBasedTest.scala
> +        forAll(knifeGen) { (mayBeKnife: Option[Knife.type ]) => {
попробуй написать стаф комбинатор, который сразу вернет лист стфа. 
B значение из конфига генератров лучше не использовать, т.к.  он нужен для всех  генераторов. Если тебе нужен  какой-то параметр для отдельного генератора, заведи для него отдельниый конфиг  или просто параметр внутри теста.

2017-03-31 09:47 UTC, sergeypopov83 commented on src/test/scala/lectures/matching/SortingStuffGeneratorBasedTest.scala
> +        val ms = generatorDrivenConfig.minSuccessful
тоже самоме про конфиг.
Вообще minSuccessful имеет совсем дургую семантику и не предназначен для задания кола-ва элементов
Есть генератоп ListOfN для этого

2017-04-02 18:58 UTC, vatt2001 requested changes

2017-04-02 18:58 UTC, vatt2001 commented on src/test/scala/lectures/matching/SortingStuffGeneratorBasedTest.scala
> +        forAll(knifeGen, stuffGen) { (mayBeKnife: Option[Knife.type], stuff) => {
Можно еще проще - написать один генератор, который будет возвращать либо нож, либо другой стафф, и именно его здесь использовать.

2017-04-04 11:04 UTC, pakondratyuk commented on src/test/scala/lectures/matching/SortingStuffGeneratorBasedTest.scala
> +        forAll(knifeGen, stuffGen) { (mayBeKnife: Option[Knife.type], stuff) => {
Сделал

2017-04-05 08:01 UTC, merged