HomeTask 7
pakondratyuk/scala-school pull request #7
Opened 2017-04-15 22:24 UTC by pakondratyuk

2017-04-20 21:01 UTC, vatt2001 requested changes

2017-04-20 21:01 UTC, vatt2001 commented on src/main/scala/lectures/concurrent/Smooth.scala
> +      var i = 0
лишняя переменная

2017-04-20 21:01 UTC, vatt2001 commented on src/main/scala/lectures/concurrent/Smooth.scala
> +      is_running.set(true)
А если прямо перед этим вызовом в другом потоке кто-то так же успеет войти в эту же критическую секцию?

2017-04-20 21:01 UTC, vatt2001 commented on src/main/scala/lectures/concurrent/Smooth.scala
> +   var resut: AtomicReference[Future[T]] = new AtomicReference[Future[T]](null)
Здесь можно везде val вместо var

2017-04-20 21:01 UTC, vatt2001 commented on src/main/scala/lectures/oop/types/GeneralBST.scala
> +        case None => None
Весь match можно заменить на `left.map(_.find(newValue))`

2017-04-20 21:01 UTC, vatt2001 commented on src/main/scala/lectures/oop/types/GeneralBST.scala
> +    if(applicator.compare(newValue, value) < 0)
`else if`?

2017-04-26 23:19 UTC, vatt2001 requested changes

2017-04-26 23:19 UTC, vatt2001 commented on src/main/scala/lectures/concurrent/Smooth.scala
> +   var resut: AtomicReference[Future[T]] = new AtomicReference[Future[T]](null)
null как значение в скале не приветствуется, ибо есть Option

2017-04-26 23:19 UTC, vatt2001 commented on src/main/scala/lectures/concurrent/Smooth.scala
> +   def apply(): Future[T] = if (is_running.getAndSet(true)) resut.get() else {
Это все равно не избавит нас от проблем, что второй поток может прочитать f как null, даже если is_running будет = true.

2017-04-26 23:19 UTC, vatt2001 commented on src/main/scala/lectures/concurrent/Smooth.scala
> +   var resut: AtomicReference[Future[T]] = new AtomicReference[Future[T]](null)
И еще предлагаю все-таки избавиться от null-а

2017-04-29 09:29 UTC, vatt2001 requested changes

2017-04-29 09:29 UTC, vatt2001 commented on src/main/scala/lectures/concurrent/Smooth.scala
> +            case _ => is_running.set(false)
Зачем обнулять is_running? это же по факту - флаг, запускалась ли фьюча на исполнение.
И если этот флаг обнулять, то фьюча может запускаться несколько раз.

2017-05-05 22:48 UTC, vatt2001 requested changes

2017-05-05 22:48 UTC, vatt2001 commented on src/main/scala/lectures/concurrent/Smooth.scala
> +            case _ => is_running.set(false)
Если позволять перезапускать вычисления, то надо переинициализировать наш промис. И делать это атомарно. И вот здесь нам помогут атомикреференсы.
А заодно надо бы спрятать локальные переменные от внешнего наблюдателя.

2017-05-10 13:49 UTC, sergeypopov83 commented on src/main/scala/lectures/concurrent/Smooth.scala
> +            case _ => is_running.set(false)
@vatt2001 Артем, в этом и задача. Если фьча запущена, не запускать, если не запущена -  запустить.

2017-05-10 13:49 UTC, sergeypopov83 commented on src/main/scala/lectures/concurrent/Smooth.scala
> +      if (is_running.getAndSet(true)) res.future
Promise должен быть разный.  Ты возвращаешь res.future , как только она станет completed, больше закомплитить ее нельзя.
Т.е. res.future - это всегда фьюча с первым закомпличенным значением, а тебе нужны новые после следуещего выполнения thunk

2017-05-10 13:49 UTC, sergeypopov83 commented on src/main/scala/lectures/concurrent/Smooth.scala
> +         res.updateAndGet(new UnaryOperator[Promise[T]] {
Раз у тебя уже есть барьер в виде is_running.getAndSet(true) и только один поток может влезть в инициализацию нового промиса, его можно сделать @volatile var res= Promise[T]()  или, если оставить атомиком, делать ему просто set без updateAndGet (updateAndGet -  это spin lock, а  это для проца не очень в некоторых случаях  может быть )
Но в общем и так работать будет конечно..

2017-05-11 07:58 UTC, merged